export { default as grassImg } from './6.jpg'
export { default as glassImg } from './4.png'
export { default as dirtImg } from './3.jpg'
export { default as logImg } from './2.jpg'
export { default as woodImg } from './5.png'
export {default as brionesImg} from './1.jpg'